Add OP Stack contracts to ChainConstants.contracts
wagmi-dev/viem pull request #1088
Opened 2023-08-30 13:32 UTC by wilsoncusack

This will unlock improved APIs and typing in [op-viem](https://github.com/base-org/op-viem).

2023-08-30 15:19 UTC, tmm reviewed
If we do something like this, might be better if this is a part of `defineChain`'s `config` parameter and inferred onto `Chain` since not all chains would have these contracts.

2023-08-30 17:24 UTC, roninjin10 requested changes
this is amazing! Long overdue

2023-08-30 17:24 UTC, roninjin10 commented on src/types/chain.ts
> +    optimismMintableErc721Factory?: Address
```suggestion
    // L1 OP Stack Contracts
    optimismL1CrossDomainMessenger?: {
      [chainId: number]: unknown
    }
    optimismL1Erc721Bridge?: {
      [chainId: number]: unknown
    }
    optimismL1StandardBridge?: {
      [chainId: number]: unknown
    }
    optimismL2OutputOracle?: {
      [chainId: number]: unknown
    }
    optimismMintableErc20Factory?: {
      [chainId: number]: unknown
    }
    optimismPortal?: {
      [chainId: number]: unknown
    }
    optimismSystemConfig?: {
      [chainId: number]: unknown
    }
    optimismSystemDictator?: {
      [chainId: number]: unknown
    }
    // L2 OP Stack Contracts
    // note these are redeploys and always have the same address
    optimismL2CrossDomainMessenger?: Address
    optimismL2StandardBridge?: Address
    optimismMintableERC20Factory?: Address
    optimismGasPriceOracle?: Address
    optimismL1Block?: Address
    optimismL2ToL1MessagePasser?: Address
    optimismL2Erc721Bridge?: Address
    optimismMintableErc721Factory?: Address
```
I think we should prefix all optimism addresses with optimism or OP.
Should the address types be `Address | undefined`?

2023-08-30 17:39 UTC, wilsoncusack commented
> If we do something like this, might be better if this is a part of `defineChain`'s `config` parameter and inferred onto `Chain` since not all chains would have these contracts.

That makes sense, thanks. Doing that well may be beyond my TS abilities :) Will also wait for @jxom to chime in as I am porting over some work he had done.

2023-08-30 18:20 UTC, tmm commented
@wilsoncusack no worries. @jxom and i can discuss and see what the best approach is.

2023-08-30 18:51 UTC, wilsoncusack commented on src/types/chain.ts
> +    optimismMintableErc721Factory?: Address
yes good call

2023-09-01 00:32 UTC, jxom commented
Closing for now. Decided it is best for these to belong in `op-viem`.

2023-09-01 00:32 UTC, closed without merging