feat(add-chain): adding vechain network to the chain list
wagmi-dev/viem pull request #1116
Opened 2023-09-01 13:40 UTC by darrenvechain

2023-09-01 18:49 UTC, tmm requested changes
Please add a patch changeset with `pnpm changeset`. See the instructions here: https://github.com/wagmi-dev/viem/blob/main/.github/CONTRIBUTING.md#4-export-your-chain

2023-09-01 18:49 UTC, tmm commented on src/chains/definitions/vechain.ts
Also need to run `pnpm lint:fix`. This file looks like it has formatting issues.

2023-09-01 18:52 UTC, tmm requested changes
Should run `pnpm test src/chains/index.test.ts`

2023-09-03 21:17 UTC, jxom commented
Thanks for the PR! Can you please re-open this pull request with @tmm's requested changes? (Closing for now to prevent stale PRs)

2023-09-03 21:17 UTC, closed without merging