perf/refactor: rlp
wagmi-dev/viem pull request #1215
Opened 2023-09-17 23:02 UTC by jxom

This PR aims to refactor our RLP coding implementation to be _a lot_ faster by using cursors instead of concating arrays (ie. copies).

h/t to @fubhy for the `Object.create` perf boost in `cursor.ts`.

<img width="787" alt="Screenshot 2023-09-18 at 8 59 41 am" src="https://github.com/wagmi-dev/viem/assets/7336481/66a84a08-0924-4a98-9170-5953c541b29a">

<img width="811" alt="Screenshot 2023-09-18 at 9 01 19 am" src="https://github.com/wagmi-dev/viem/assets/7336481/0e79edc2-3da0-4d8e-8038-ff5b6b96f601">

2023-09-19 02:57 UTC, fubhy requested changes

2023-09-19 02:57 UTC, fubhy commented on src/utils/encoding/toBytes.bench.ts
> +const generateBytes = (length: number) => {
You could consider using https://www.npmjs.com/package/fast-check for your generating, fuzzing and bench input scenarios.

2023-09-19 02:57 UTC, fubhy commented on src/utils/encoding/toBytes.ts
> +  }
This is good. As discussed, given wrongly encoded input to `Buffer.from` doesn't fail as it should (imho). So I appreciate that `isHex` check before that call for correctness.

To be sure that we are decoding correctly and the output between Buffer.from and the custom implementation is identical I'd suggest to add a test that fuzzes both. But that would require splitting it up here.

2023-09-19 02:57 UTC, fubhy commented on src/utils/encoding/toHex.ts
> +  })()
This function can be externalized. Safe some memory & performance.

Also, I'd put the check for (`'Buffer' in globalThis && typeof Buffer.from === 'function'`) into a const somewhere and use that in these two functions (and wherever else it might be used). Checking a boolean is always faster :)

2023-09-19 02:57 UTC, fubhy commented on src/utils/encoding/toRlp.ts
> +    },
This could also use `Object.create`

2023-09-19 02:57 UTC, fubhy commented on src/utils/encoding/toRlp.ts
> +  }
Same here.

2023-09-19 02:57 UTC, fubhy commented on vectors/src/rlp.ts
> +export async function generateRlpVectors() {
Check out https://www.npmjs.com/package/fast-check

2023-09-19 03:20 UTC, fubhy commented on src/utils/encoding/toBytes.ts
> +  }
You could also consider doing sth. like

```ts
export const hexToBytes: (hex_: Hex, opts: HexToBytesOpts = {}): ByteArray = hasBuffer ? hexToBytesBuffer : hexToBytesCustom;

2023-09-24 02:34 UTC, paulmillr commented
Could you add benchmarks against community-standard https://www.npmjs.com/package/@ethereumjs/rlp ?

2023-09-24 03:47 UTC, jxom commented
@paulmillr – good idea, can do!

2023-09-24 04:14 UTC, jxom commented
Seems pretty on-par for encoding:

<img width="1314" alt="Screenshot 2023-09-24 at 2 08 47 pm" src="https://github.com/wagmi-dev/viem/assets/7336481/4288863e-5a15-4407-abca-e0e97b45ed5a">

Maybe some room for improvement for decoding:

<img width="1351" alt="Screenshot 2023-09-24 at 2 09 31 pm" src="https://github.com/wagmi-dev/viem/assets/7336481/1b3e8669-c5dc-40cc-a042-e0075ed70b6e">

These benches are for `Uint8Array` → `Uint8Array`.

Could be worth contributing back to ethereumjs here – can look more closely when I find some time.

2023-09-24 13:25 UTC, paulmillr commented
Thanks, that sounds interesting!

2023-09-24 20:56 UTC, merged

2023-09-24 21:36 UTC, paulmillr commented
@jxom How does this `Buffer` addition work with bundlers? In my experience some bundlers could see this and auto-include buffer polyfills.

I would strongly recommend against buffers, because they have security issues.

2023-09-24 21:45 UTC, jxom commented
Fair call. Don't think the perf gain is much of an improvement after your change. Will remove.