Chore: Add missing ethers.js constants
wagmi-dev/viem pull request #1475
Opened 2023-11-09 18:04 UTC by xtools-at

2023-11-09 18:14 UTC, xtools-at commented
asked for in #447 and #667

2023-11-09 21:29 UTC, jxom requested changes
Think `zeroHash` and `messagePrefix` may be the useful ones here.

2023-11-09 21:29 UTC, jxom commented on src/constants/number.ts
> +  0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141n
I'm not too sure I see much value in these apart from `weiPerEther` which we already export in `src/constants/unit.ts`

2023-11-09 21:29 UTC, jxom commented on src/constants/strings.ts
> +export const etherSymbol = 'Ξ'
I'm not sure if we need to export this. Can't consumers just google "ether symbol"?

2023-11-09 21:29 UTC, jxom commented on src/constants/strings.ts
> +export const messagePrefix = '\x19Ethereum Signed Message:\n'
Can we import this in `src/utils/signature/hashMessage.ts`?

2023-11-09 21:29 UTC, jxom commented on src/constants/bytes.ts
> +export const hashZero =
```suggestion
export const zeroHash =
```

2023-11-09 21:29 UTC, jxom commented on src/constants/strings.ts
> +export const messagePrefix = '\x19Ethereum Signed Message:\n'
```suggestion
export const presignMessagePrefix = '\x19Ethereum Signed Message:\n'
```

2023-11-10 09:28 UTC, xtools-at commented
committed requested changes

2023-11-12 00:33 UTC, merged